Purpur > Paper
Bloom-host/BloomDocs pull request #230
Opened 2022-09-07 17:18 UTC by zax71

2022-09-11 17:16 UTC, Evidentsinger14 requested changes
> For the Bukkit platform you mave many 
```diff
- mave
+ have
```
> If you want peformance tewaks on top that can be powerful but may break the more technical mechanics or quality of life tweaks try 
```diff
- If you want peformance tewaks on top that can be powerful but may break the more technical mechanics or quality of life tweaks try [Purpur](https://purpurmc.org/downloads).
+ If you want performance tweaks that can be powerful, but may break the more technical mechanics or quality of life tweaks try [Purpur](https://purpurmc.org/downloads).
```

2022-09-11 17:17 UTC, Evidentsinger14 commented
@zax71 i didn't see any other spelling/grammar errors, but i'll have another look in a few minutes.

2022-10-12 10:01 UTC, democracycraft commented on docs/running_a_server/optimization.md
> +For the Bukkit platform you mave many options for a server jar, the most stable of which is [Paper](https://papermc.io). Paper includes many performance improvements, bug fixes and configuration opti
Small typo here, I think you meant 'have' not 'mave'!

2022-10-12 14:29 UTC, zax71 commented
Thanks for pointing that out, I’ll fix it when I get time!

On Wed, 12 Oct 2022 at 11:01 am, democracycraft ***@***.***>
wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In docs/running_a_server/optimization.md
> <https://github.com/Bloom-host/BloomDocs/pull/230#discussion_r993257102>:
>
> > @@ -44,7 +44,7 @@ re just going to outline the two best known "paths", the bukkit platform, and fa
>  The gist of it is the bukkit platform is generally recommended for bigger public servers and fabric for smaller servers with friends.
>  The bukkit platform allows you to use plugins, and fabric allows you to run mods.
>
> -For the bukkit platform the [Paper](https://papermc.io/) jar is recommended, it includes many performance improvements, bug fixes and configuration options
> +For the Bukkit platform you mave many options for a server jar, the most stable of which is [Paper](https://papermc.io). Paper includes many performance improvements, bug fixes and configuration options. If you want peformance tewaks on top that can be powerful but may break the more technical mechanics or quality of life tweaks try [Purpur](https://purpurmc.org/downloads).
>
> Small typo here, I think you meant 'have' not 'mave'!
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Bloom-host/BloomDocs/pull/230#pullrequestreview-1138805136>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AQEUJJ4OCK6MXCATIUEBAKTWC2EAHANCNFSM6AAAAAAQG656RI>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-05-21 13:31 UTC, merged